services:
  meshlink:
    build:
      context: .
    container_name: meshlink
    depends_on:
      - db
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MYSQL_SERVER: "db"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
      NODENAME: Meshlink Alpha
      IP: 270.0.0.1
      LATITUDE: 0
      LONGITUDE: 0
      PORT: 5000
      PREFIX: /
      FLOOD_ADVERT_ON_START: false
    volumes:
      - meshlink:/data
  db:
    image: mysql:latest
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
  meshlink: