services:
   server:
     build:
       context: .
     environment:
       NODE_ENV: production
       NODENAME: "MeshLink Alpha"
       IP: "127.0.0.0"
       LATITUDE: 0.0
       LONGITUDE: 0.0
       PORT: 5000
       PREFIX: "/"
       FLOOD_ADVERT_ON_START: false