services:
  meshlink:
    image: rubymetro/meshlink:latest
    container_name: meshlink
    ports:
      - "5000:5000"
    environment:
      - NODENAME=Meshlink Alpha
      - IP=270.0.0.0
      - LATITUDE=0
      - LONGITUDE=0
      - PORT=5000
      - PREFIX=/
      - FLOOD_ADVERT_ON_START=false
    restart: unless-stopped